# generated by http://restunited.com
# for any feedback/issue with the code, please contact support{at}restunited.com

# initialize the API client

import re
from collections import Counter, defaultdict
import os
from pprint import pprint
from html.parser import HTMLParser

machine_females = open(os.path.join(os.environ["AAN_DIR"],"machine_femalesNAM.txt"),"w", encoding="utf-8")
machine_males = open(os.path.join(os.environ["AAN_DIR"],"machine_malesNAM.txt"),"w", encoding="utf-8")
machine_unsure = open(os.path.join(os.environ["AAN_DIR"],"machine_unsure.txt"),"w", encoding="utf-8")
pars = HTMLParser()
with open(os.path.join(os.environ["AAN_DIR"],"namresults.txt"),"r", encoding="utf-8") as f:
    unknown_names = f.read().split("\n")
    males=0
    females=0
    new_unk = set()
    p = re.compile("\(u.(.+)., '(.*)', (.*)\)")

    for line in unknown_names:

        if not line: continue
        
        m = p.match(line)
       

        name = pars.unescape(m.group(1))
        gender = m.group(2).strip()
        scale = float(m.group(3))
        if gender == "unknown": continue
        if(abs(scale) < 0.5): 
            machine_unsure.write(line + "\n")
            continue
        if gender == "female":
            machine_females.write(name + "\n")
            females += 1
        elif gender == "male":
            machine_males.write(name + "\n")
            males += 1

    print(males, females)
       

