#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Name(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'country': 'str',
            'country_alt': 'str',
            'country_first_name': 'str',
            'country_last_name': 'str',
            'country_name': 'str',
            'first_name': 'str',
            'gender': 'str',
            'id': 'str',
            'last_name': 'str',
            'region': 'str',
            'scale': 'float',
            'score': 'float',
            'score_first_name': 'float',
            'score_last_name': 'float',
            'script': 'str',
            'sub_region': 'str',
            'top_region': 'str'

        }

        self.attributeMap= {
            'country': 'country',
            'country_alt': 'countryAlt',
            'country_first_name': 'countryFirstName',
            'country_last_name': 'countryLastName',
            'country_name': 'countryName',
            'first_name': 'firstName',
            'gender': 'gender',
            'id': 'id',
            'last_name': 'lastName',
            'region': 'region',
            'scale': 'scale',
            'score': 'score',
            'score_first_name': 'scoreFirstName',
            'score_last_name': 'scoreLastName',
            'script': 'script',
            'sub_region': 'subRegion',
            'top_region': 'topRegion'

        }

        #Country
        self.country = None # str
        #Countryalt
        self.country_alt = None # str
        #Countryfirstname
        self.country_first_name = None # str
        #Countrylastname
        self.country_last_name = None # str
        #Countryname
        self.country_name = None # str
        #Firstname
        self.first_name = None # str
        #Gender
        self.gender = None # str
        #ID
        self.id = None # str
        #Lastname
        self.last_name = None # str
        #Region
        self.region = None # str
        #Scale
        self.scale = None # float
        #Score
        self.score = None # float
        #Scorefirstname
        self.score_first_name = None # float
        #Scorelastname
        self.score_last_name = None # float
        #Script
        self.script = None # str
        #Subregion
        self.sub_region = None # str
        #Topregion
        self.top_region = None # str
        
